spring:
  datasource:
    url: jdbc:postgresql://db:5432/library_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.yaml

logging:
  level:
    liquibase: DEBUG
    org.springframework.jdbc.core: TRACE
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret-key: "MySuperSecretKeyForJWTGenerationThatIsLongEnough"
  expiration-time: 86400000