spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.yaml
  jdbc:
    template:
      fetch-size: 100
      max-rows: 1000
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    liquibase: DEBUG
    org.springframework.jdbc.core: TRACE
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true

  springdoc.swagger-ui.path: /swagger-ui.html
  springdoc.swagger-ui.enabled: true
  springdoc.api-docs.path: /v3/api-docs
  springdoc.swagger-ui.url: /v3/api-docs
  springdoc.swagger-ui.configUrl: /v3/api-docs/swagger-config
